const fs=require('fs'),path=require('path'),assert=require('assert/strict');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const raw=fs.readFileSync(path.join(__dirname,'../app/src/main/assets/auto_login.js'),'utf8');
const script=attempt=>raw.replaceAll('__USER__',JSON.stringify('fixture-user')).replaceAll('__PASS__',JSON.stringify('fixture-password')).replaceAll('__ATTEMPT__',String(attempt));
const fixture=`<form id="pwdFromId" action="https://id.hqu.edu.cn/authserver/login"><input id="pwdEncryptSalt" value="fixture-salt"><input name="username"><input name="passwordText"><input name="password"><input name="captcha"></form><div id="showErrorTip" style="display:none"></div>`;
(async()=>{
 const browser=await chromium.launch({headless:true,channel:process.env.PLAYWRIGHT_CHANNEL||'msedge'});let passed=0,failed=0;
 async function page(){const p=await browser.newPage();await p.clock.install();await p.setContent(fixture);await p.evaluate(()=>{window.submits=0;HTMLFormElement.prototype.submit=function(){window.submits++;};window.encryptPassword=()=> 'fixture-ciphertext';window.fetch=async()=>({json:async()=>({isNeed:false})});});return p;}
 async function run(name,test){const p=await page();try{await test(p);passed++;console.log('PASS '+name);}catch(e){failed++;console.log('FAIL '+name+': '+e.message);}finally{await p.close();}}
 const result=p=>p.evaluate(()=>JSON.parse(window.__LOGIN_RESULT));
 await run('slow redirect is pending, not password rejection at ten seconds',async p=>{await p.evaluate(script(1));await p.clock.runFor(11000);assert.equal((await result(p)).ok,true);assert.equal(await p.evaluate(()=>submits),1);});
 await run('duplicate page-finished injection cannot double submit',async p=>{await p.evaluate(script(1));await p.evaluate(script(1));assert.equal(await p.evaluate(()=>submits),1);});
 await run('terminal error releases guard and explicit new attempt can submit',async p=>{await p.evaluate(()=>{window.encryptPassword=()=>{throw new Error('fixture failure');};});await p.evaluate(script(1));assert.equal((await result(p)).ok,false);assert.equal(await p.evaluate(()=>window.__LOGIN_RUNNING),false);await p.evaluate(()=>{window.encryptPassword=()=> 'fixture-ciphertext';});await p.evaluate(script(2));assert.equal(await p.evaluate(()=>submits),1);assert.equal((await result(p)).attempt,2);});
 await run('visible server rejection is reported without another submission',async p=>{await p.evaluate(()=>{const e=document.getElementById('showErrorTip');e.style.display='block';e.textContent='账号暂时锁定';});await p.evaluate(script(1));assert.equal(await p.evaluate(()=>submits),0);assert.equal((await result(p)).stage,'server_rejected');});
 await run('obsolete async attempt cannot submit or replace newer result',async p=>{await p.evaluate(()=>{let n=0;window.fetch=()=>{if(++n===1)return new Promise(r=>window.releaseOld=()=>r({json:async()=>({isNeed:false})}));return Promise.resolve({json:async()=>({isNeed:false})});};});await p.evaluate(script(1));await p.evaluate(script(2));await p.evaluate(()=>releaseOld());await p.clock.runFor(10);assert.equal(await p.evaluate(()=>submits),1);assert.equal((await result(p)).attempt,2);});
 await run('missing form remains recoverable',async p=>{await p.setContent('<p>loading</p>');await p.evaluate(script(1));await p.clock.runFor(11000);assert.equal((await result(p)).stage,'no_form');assert.equal(await p.evaluate(()=>window.__LOGIN_RUNNING),false);});
 await run('HTTP CAS form is upgraded before credentials are submitted',async p=>{await p.evaluate(()=>document.getElementById('pwdFromId').action='http://id.hqu.edu.cn:80/authserver/login?service=fixture');await p.evaluate(script(1));assert.equal(await p.evaluate(()=>new URL(document.getElementById('pwdFromId').action).protocol),'https:');assert.equal(await p.evaluate(()=>submits),1);});
 await run('untrusted form cannot receive credentials',async p=>{await p.evaluate(()=>document.getElementById('pwdFromId').action='https://evil.test/authserver/login');await p.evaluate(script(1));assert.equal(await p.evaluate(()=>submits),0);assert.equal((await result(p)).stage,'invalid_action');});
 await browser.close();console.log(`Login browser regressions: ${passed} passed, ${failed} failed`);if(failed)process.exit(1);
})().catch(e=>{console.error(e);process.exit(1);});
